# Generated by Django 5.2.7 on 2025-10-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0003_task_label_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(related_name='task', to='label.label'),
        ),
    ]
