# Generated by Django 5.2.7 on 2025-10-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0006_alter_task_author_alter_task_executor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='labels', to='label.label', verbose_name='Метки'),
        ),
    ]
